### ISSUE TITLE
query filter by Key fails with unsupported error

### ISSUE THREAD

**Issue by mark1010** [dart-lang/gcloud#23]
filtering by Key fails with 'Cannot encode unsupported Key type.'

gcloud 0.1.3+1, appengine 0.2.5

	@Kind(name:'m_channel')  
	class Channel extends Model { 
 		@StringProperty()
  		String name;
	}

	@Kind(name:'m_data')
	class Data extends Model {
		@DoubleProperty()
  		double value;

  		@ModelKeyProperty()
  		Key channelKey; 
 	}

query

    Query q = new Query(db,Data);
    q.filter('channelKey =', channelKey);
	q.run().toList();

fails with
	
	DEBUG: Container: 4418e6f400e7: 2015-02-04 10:07:15.409: ApplicationLog | Error: Uncaught error in request handler: ApplicationError: Cannot encode unsupported Key type.
	#0      Codec.encodeProperty (package:appengine/src/api_impl/raw_datastore_v3_impl.dart:319:7)
	#1      DatastoreV3RpcImpl.query (package:appengine/src/api_impl/raw_datastore_v3_impl.dart:527:57)
	#2      Query.run.<anonymous closure> (package:gcloud/src/db/db.dart:224:33)
	#3      _onListen (package:gcloud/common.dart:69:23)
	#4      _runGuarded (dart:async/stream_controller.dart:664)
	#5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:513)
	#6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:414)
	#7      _StreamController._subscribe (dart:async/stream_controller.dart:512)
	#8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:682)
	#9      _StreamImpl.listen (dart:async/stream_impl.dart:474)
	#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:96)
	#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:88)

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by mkustermann** [comment]
Hi Mark,

thank you for the bug report.

There is a TODO in the code which hasn't been addressed yet. I'll take a look as soon as I can.

```dart
  /**
   * Adds a filter to this [Query].
   *
   * [filterString] has form "name OP" where 'name' is a fieldName of the
   * model and OP is an operator. The following operators are supported:
   *
   *   * '<' (less than)
   *   * '<=' (less than or equal)
   *   * '>' (greater than)
   *   * '>=' (greater than or equal)
   *   * '=' (equal)
   *   * 'IN' (in - `comparisonObject` must be a list)
   *
   * [comparisonObject] is the object for comparison.
   */
  void filter(String filterString, Object comparisonObject) {
    var parts = filterString.split(' ');
    if (parts.length != 2 || !_relationMapping.containsKey(parts[1])) {
      throw new ArgumentError(
          "Invalid filter string '$filterString'.");
    }

    // TODO: do value transformation on [comparisionObject]

    var propertyName = _convertToDatastoreName(parts[0]);
    _filters.add(new datastore.Filter(
        _relationMapping[parts[1]], propertyName, comparisonObject));
  }
```

**Comment by mkustermann** [comment]
CL is up for review: https://codereview.chromium.org//868113006

**Comment by sigurdm** [comment]
Did this ever land? Can we close this?
