### ISSUE TITLE
Test gcloud/test/storage/e2e_test can fail

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/gcloud#27]
```
FAILED: none-vm release_ia32 gcloud/test/storage/e2e_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done
PASS: object create-read-delete
PASS: object create-with-predefined-acl-delete
PASS: object create-with-acl-delete
PASS: object create-with-metadata-delete

All 4 tests passed.
unittest-suite-success


stderr:
Unhandled exception:
Uncaught Error: DetailedApiRequestError(status: 409, message: The bucket you tried to delete was not empty.)
Stack Trace:
#0      _validateResponse.<anonymous closure> (package:googleapis/src/common_internal.dart:880:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1155)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:567)
#4      _Future._complete (dart:async/future_impl.dart:348)
#5      _cancelAndValue (dart:async/stream_pipe.dart:62)
#6      Stream.first.<anonymous closure> (dart:async/stream.dart:911)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#12     _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1417)
#13     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:93)
#14     _handleDone (dart:async/stream_transformers.dart:140)
#15     _RootZone.runGuarded (dart:async/zone.dart:1082)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:95)
#20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:18)
#21     _StringAdapterSink.close (dart:convert/string_conversion.dart:267)
#22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:324)
#23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:93)
#24     _handleDone (dart:async/stream_transformers.dart:140)
#25     _RootZone.runGuarded (dart:async/zone.dart:1082)
#26     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#27     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#28     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#29     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:112)
#30     _handleDone (dart:async/stream_pipe.dart:180)
#31     _RootZone.runGuarded (dart:async/zone.dart:1082)
#32     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#33     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#34     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#35     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:95)
#36     _EventSinkWrapper.close (dart:async/stream_transformers.dart:18)
#37     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:68)
#38     _FilterSink.close (dart:io/data_transformer.dart:523)
#39     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:93)
#40     _handleDone (dart:async/stream_transformers.dart:140)
#41     _RootZone.runGuarded (dart:async/zone.dart:1082)
#42     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#43     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#44     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#45     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:112)
#46     _handleDone (dart:async/stream_pipe.dart:180)
#47     _rootRun (dart:async/zone.dart:895)
#48     _RootZone.runGuarded (dart:async/zone.dart:1084)
#49     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:390)
#50     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)
#51     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#52     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:706)
#53     _StreamController._closeUnchecked (dart:async/stream_controller.dart:559)
#54     _StreamController.close (dart:async/stream_controller.dart:552)
#55     _HttpParser._closeIncoming (dart:io/http_parser.dart:1023)
#56     _HttpParser._doParse (dart:io/http_parser.dart:733)
#57     _HttpParser._parse (dart:io/http_parser.dart:330)
#58     _onData (dart:io/http_parser.dart:792)
#59     _rootRunUnary (dart:async/zone.dart:902)
#60     _CustomZone.runUnary (dart:async/zone.dart:804)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#64     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#65     _StreamController._add (dart:async/stream_controller.dart:570)
#66     _StreamController.add (dart:async/stream_controller.dart:516)
#67     _onData (dart:io-patch/socket_patch.dart:1764)
#68     _rootRunUnary (dart:async/zone.dart:902)
#69     _CustomZone.runUnary (dart:async/zone.dart:804)
#70     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
#71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#73     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#74     _StreamController._add (dart:async/stream_controller.dart:570)
#75     _StreamController.add (dart:async/stream_controller.dart:516)
#76     _sendReadEvent (dart:io/secure_socket.dart:1137)
#77     _rootRun (dart:async/zone.dart:891)
#78     _CustomZone.run (dart:async/zone.dart:796)
#79     _CustomZone.runGuarded (dart:async/zone.dart:704)
#80     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
#81     _rootRun (dart:async/zone.dart:895)
#82     _CustomZone.run (dart:async/zone.dart:796)
#83     _CustomZone.runGuarded (dart:async/zone.dart:704)
#84     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:729)
#85     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#86     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#87     _handleMessage (dart:isolate-patch/timer_impl.dart:411)
#88     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:392)
#5      _handleMessage (dart:isolate-patch/timer_impl.dart:411)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)


Command[vm]: DART_CONFIGURATION=ReleaseIA32 xcodebuild/ReleaseIA32/dart-sdk/bin/dart --ignore-unrecognized-flags --package-root=xcodebuild/ReleaseIA32/package_copy/gcloud/packages /Volumes/data/b/build/slave/packages-mac-gcloud/build/dart/xcodebuild/ReleaseIA32/package_copy/gcloud/test/storage/e2e_test.dart
Took 0:00:15.389000

Short reproduction command (experimental):
    python tools/test.py -mrelease --suite-dir xcodebuild/ReleaseIA32/package_copy/gcloud --use-sdk --clear_browser_cache --package-root xcodebuild/ReleaseIA32/package_copy/gcloud/packages --write-debug-log -t60 gcloud/test/storage/e2e_test
```

**Comment by sigurdm** [comment]
Closing as obsolete. Please open a new issue if this is still relevant.
